config/routes.rb
Rails.application.routes.draw do
  root to: "flats#home"
  devise_for :users, :controllers => { registrations: 'registrations' }
  get :my_profile, to: "users#my_profile"

  resources :flats do
    resources :bookings, only: [:new, :show, :create, :destroy] do
    end
  end

  resources :flats do []
    resources :reviews, only: :show
  end

  resources :bookings, only: [] do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  has_many :reviews
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  geocoded_by :address
  after_validation :geocode
  # validates :description, :price, :city, :zipcode, :street, :pictures, presence: true
  # validates :key_description, length: { in: 3..35 }
  # validates :description, length: { minimum: 150 }
  mount_uploaders :pictures, PictureUploader

  def address
    [street, city, zipcode].compact.join(', ')
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }, presence: true
  validates :content, length: { in: 20..100 }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :bookings
  has_many :reviews, through: :bookings
  has_many :flats, dependent: :destroy
  validates :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  # before_action :authenticate_user!
  # include Pundit

  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password,
  #     :password_confirmation, :remember_me) }
  #   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password,
  #     :password_confirmation, :current_password) }
  # end
  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flat = Flat.find(params[:flat_id])
    redirect_to flat_bookings_path(@flat)
  end

  def create
    @booking = Booking.new
    @booking.user = current_user
    @flat = Flat.find(params[:flat_id])
    @booking.flat = @flat

    if @booking.save
      redirect_to my_profile_path
    else
      redirect_to flat_path(@flat)
    end
  end
  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to my_profile_path
    else
      render :new
    end
  end

  private

  def bookings_params
    # FIXME
    params.require(:booking).permit(:checkin, :checkout, :guests)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def home
    @flats = Flat.all

  end

  def index
    @flats = if params[:city]
       Flat.where('city LIKE ?', "%#{params[:city]}%")
     else
       Flat.all
     end
    # @flats = Flat.where.not(latitude: nil, longitude: nil)
    @markers = @flats.map do |flat|
      {
        lng: flat.longitude,
        lat: flat.latitude,
        infoWindow: { content: render_to_string(partial: "/shared/map_window", locals: { flat: flat }) }
      }
    end
  end

  def show
    @booking = Booking.new
    @flat.reviews
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to @flat
    else
      render :new
    end
  end

  def edit
    puts "hello from edit"
  end

  def update
    @flat.update(flat_params)
    redirect_to @flat
  end

  def destroy
    @flat = Flat.find(params[:id])
    if @flat.destroy
      redirect_to my_profile_path
    else
      render :edit
    end
  end

  private

# <<<<<<< HEAD
# =======
#   def set_flat
#     @flat = Flat.find(params[:id])
#   end

# >>>>>>> 4a7a3013187c4f535c1cbe7c737d738d1b724817
def flat_params
  params.require(:flat).permit(:key_description, :description, :price, :city, :zipcode, :street, :country, :average_rating, :wifi, :dishwasher, :allows_pets, :kitchen, :guests, :handicap, :balcony, :smoking, :tv, :availability, {pictures: []})
end

def set_flat
  @flat = Flat.find(params[:id])
end

# =======
#   private
#   def flat_params
#     params.require(:flat).permit(:description, :price, :city, :zipcode, :street, :country, :average_rating, :wifi, :dishwasher, :allows_pets, :kitchen, :guests, :handicap, :balcony, :smoking, :tv, :availability, {pictures: []})
#   end
# >>>>>>> 629e631d084e1f037df0a61bf7d1d416cacae8ae
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :photo)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new()
  end

  def create
    @flats = Flat.all
    @review = Review.new(review_params)
    @review.booking = Booking.find(params[:booking_id])
    redirect_id = @review.booking.flat.id
    if @review.save
      redirect_to flat_path(redirect_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  private

  def set_flat
    @review = Review.find(params[:id])
    authorize @review
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_profile
    @user = current_user
    @user_bookings = current_user.bookings if current_user.present?
    @user_flats = current_user.flats
    @flats = Flat.all
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
      <ul class="inbox">
        <li class="message">
          <img src="images/gab.png" alt="" class="avatar-large">
          <div class="message-name">
            <h3>Gab Dehan</h3>
            <p>10/07/17</p>
          </div>
          <div class="message-body">
            <p><strong>I am not sure yet!</strong></p>
            <p>
              I am not sure yet! I might be in Shanghai at this moment... Can I tell you later?
            </p>
          </div>
          <div class="message-status">
            <p class="status pending">Pending</p>
            <p class="price">€345</p>
          </div>
        </li>
        <li class="message">
          <img src="images/cecile.png" alt="" class="avatar-large">
          <div class="message-name">
            <h3>Cecile Veneziani</h3>
            <p>23/09/17</p>
          </div>
          <div class="message-body">
            <p><strong>I’ll be glad to welcome you in my cosy flat</strong></p>
            <p>
              I’ll be glad to welcome you in my cosy flat in Lille. When are you arriving exactly?
            </p>
          </div>
          <div class="message-status">
            <p class="status accepted">Accepted</p>
            <p class="price">€345</p>
          </div>
        </li>
        <li class="message">
          <img src="images/jad.png" alt="" class="avatar-large">
          <div class="message-name">
            <h3>Jad Joubran</h3>
            <p>19/08/17</p>
          </div>
          <div class="message-body">
            <p><strong>Hey man! I'm sorry...</strong></p>
            <p>
              Hey man! I'm sorry... I'll be in Amsterdam at these dates.
            </p>
          </div>
          <div class="message-status">
            <p class="status declined">Declined</p>
            <p class="price">€560</p>
          </div>
        </li>
      </ul>

app/views/flats/_picture_carousel.html.erb
<div id="pictureCarousel" class="carousel slide" data-ride="carousel" data-interval="2000" data-pause="hover">
  <ol class="carousel-indicators">
    <% @flat.pictures.each_with_index do |picture, index| %>
      <% if index == 0 %>
        <li data-target="#pictureCarousel" data-slide-to=<% index %> class="active"></li>
      <% else %>
        <li data-target="#pictureCarousel" data-slide-to=<% index %>></li>
      <% end %>
    <% end %>
  </ol>
  <div class="carousel-inner" >
    <% @flat.pictures.each_with_index do |picture, index| %>
      <% if index == 0 %>
        <div class="carousel-item active">
          <%= image_tag picture.url, class: "d-block w-100", alt: "#{index} picture" %>
        </div>
      <% else %>
        <div class="carousel-item">
          <%= image_tag picture.url, class: "d-block w-100", alt: "#{index} picture" %>
        </div>
      <% end %>
    <% end %>
  </div>
   <a class="carousel-control-prev" href="#pictureCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#pictureCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/flats/edit.html.erb
<div class="internal-banner-form" style="background-image: url( <%=image_path('room.jpg')%>);">
  <div class="internal-form-block-form">
   <div class="internal-form-inputs">
    <h1 class="book-title">Update your flat</h1>
    <%= render 'shared/form', flat: @flat %> <br>
    <div class="internal-form-actions">
      <%= link_to 'Delete Flat', flat_path(@flat), method: :delete, class: 's-button' %>
    </div>
    <br>
  </div>
</div>
</div>

app/views/flats/home.html.erb
<%= render "./shared/banner" %>
<%= render "./shared/card" %>

app/views/flats/index.html.erb
<div class="index-page" style="display: flex; position: relative;">
  <div class="index-cards" style="flex: 1;"><%= render "./shared/indexcards" %></div>
  <div
    class="index-map col-xs-6 col-sm-3 col-m-3"
    id="map"
    style="
    height: 100vh;
    position: sticky;
    top: 0;
    width: 100%;
    margin-right: 30px;
    margin-top: 20px;
    padding-left: 10px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/flats/new.html.erb
<div class="internal-banner-form" style="background-image: url( <%=image_path('room.jpg')%>);">
  <div class="internal-form-block-form">
   <div class="internal-form-inputs">
    <h1 class="book-title">Create a flat</h1>
    <%= render 'shared/form', flat: @flat %> <br>
    <div class="internal-form-actions">
    </div>
    <br>
  </div>
</div>
</div>

app/views/flats/show.html.erb
<%= render 'picture_carousel', flat: @flat %>



<div class="container-fluid flex" style="margin: 0px 0px; display: flex; justify-content: space-between; flex-wrap: wrap;">
  <%= render './shared/flat_owner_info' %>
  <%= render './shared/booking_form' %>
</div>



<div class="container-fluid flex" style="margin: 0px 0px 10px 0px; display: flex; flex-direction: row; justify-content: center; flex-wrap: wrap;">
  <%= render './shared/about_this_flat' %>
</div>

<% if @booking.reviews.present? %>
  <%= render 'reviews/show' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Flatmate</title>
    <%= favicon_link_tag 'https://res.cloudinary.com/dqssam2go/image/upload/v1542972937/fmlogo.png', :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- GOOGLE FONTS - RALEWAY -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,400,800" rel="stylesheet">

    <!-- FONTAWESOME -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- jquery -->
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <!-- ADD THIS LINE 👇 -->
  <%= stylesheet_pack_tag "application" %>
  <%= stylesheet_pack_tag "map" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "./shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <!-- ADD THIS LINE 👇 -->
    <%= javascript_pack_tag "map" %>
    <!-- BOOTSTRAP -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_show.html.erb
<div class="review-show-container">
  <h2 style="text-align: center;">Reviews</h2>
  <ul class="bookings">
    <% @flat.reviews.each do |r| %>
    <li class="booking">
      <div class="booking-name">
        <%= image_tag r.booking.user.photo.url, class: "avatar-review" %>
        <h3><%= r.booking.user.first_name %> <%= r.booking.user.last_name %></h3>
      </div>
      <div class="booking-body">
        <div class="price"><%=r.content %>
        </div>
      </div>
      <div class="booking-status">
        <div class="price">
          <% if r.rating != nil %>
          <% (r.rating).times do %>
          <i class="fas fa-star" style="color: #ffb400"></i>
          <% end %>
          <% (5 - r.rating).times do %>
          <i class="far fa-star" style="color: #ffb400"></i>
          <% end %>
          <% end %>
        </div>
        <div class="status"><%= r.created_at.strftime("%Y-%m-%d") %></div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<div class="internal-banner-form" style="background-image: url( <%=image_path('room.jpg')%>);">
  <div class="internal-form-block-form">
   <div class="internal-form-inputs">
    <h1>Create a review</h1>
   <%= render'shared/review', flat: @flat %> <br>
     <div class="internal-form-actions">
  </div>
     <br>
  </div>
    </div>
</div>

app/views/shared/-form.html.erb
<%= simple_form_for(@flat), html: { multipart: true } do |f| %>
<%= f.input :description %>
<%= f.input :city %>
<%= f.input :price %>
<%= f.input :number_of_guests %>
<%= f.label :pictures %>
<%= f.file_field :pictures, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png" %>
<%= f.submit %>
<% end %>


<%= f.check_box :wifi, :dishwasher, :pets_allowed, :kitchen, :smocking_allowed, :balcony, :tv %>

<%= f.submit "Submit" %>
<% end %>

app/views/shared/_about_this_flat.html.erb
<div class="row" id="flat-data" style="justify-content: center;">
  <h2 class="about-flat-header" id="head">About this flat</h2>
  <p class="fd"><%= @flat.description %></p>

  <div class="row">
    <div class="amenities-header">Amenities - </div>
              <div class="list">
                <ul class="list-unstyled">
                  <% if @flat.kitchen == true %>
                  <li>
                    <i class="fas fa-utensils"></i>
                    <strong>Kitchen</strong>
                  </li>
                  <% end %>
                  <% if @flat.dishwasher == true %>
                  <li>
                    <i><%= image_tag 'https://res.cloudinary.com/dqssam2go/image/upload/v1542972950/dishwasher.png', style: "width: 20px"%></i>
                    <strong>Dishwasher</strong>
                  </li>
                  <% end %>
                  <% if @flat.wifi == true %>
                  <li>
                    <i class="fas fa-wifi"></i>
                    <strong>Wifi</strong>
                  </li>
                  <% end %>
                  <% if @flat.tv == true %>
                  <li>
                    <i class="fas fa-tv"></i>
                    <strong>TV</strong>
                  </li>
                  <% end %>
                  <% if @flat.allows_pets == true %>
                  <li>
                    <i class="fas fa-paw"></i>
                    <strong>Pets</strong>
                  </li>
                  <% end %>
                  <% if @flat.handicap == true %>
                  <li>
                    <i class="fas fa-wheelchair"></i>
                    <strong>handicap accessible</strong>
                  </li>
                  <% end %>
                  <% if @flat.balcony == true %>
                  <li>
                    <i><%= image_tag 'https://res.cloudinary.com/dqssam2go/image/upload/v1542972970/balcony.png', style: "width: 20px"%></i>
                    <strong>Balcony</strong>
                  </li>
                  <% end %>
                  <% if @flat.smoking == true %>
                  <li>
                    <i class="fas fa-smoking"></i>
                    <strong>Smoking</strong>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: url( <%=image_path('https://res.cloudinary.com/dqssam2go/image/upload/v1542809419/banner_flat.jpg')%>);">
  <div class="form-block">
    <%= render "./shared/search" %>
  </div>
</div>

app/views/shared/_booking_form.html.erb
<div class="form-wrapper book-form">
  <h2 class="book-title">Book this flat</h2>
  <div class="form-group">
    <%= simple_form_for([@flat, @flat.bookings.new], method: "post") do |f| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <%= f.submit "Book it", class: "book-button" %>
    <% end %>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="container">
  <div class="row">
    <% @flats.each do |f| %>
      <div class="col-xs-12 col-sm-4 col-m-4">
        <%= link_to flat_path(f), class: "text-dec" do %>
          <div class="card">
            <div class="flat-image">
              <% if f.pictures != [] %>
                <%= image_tag f.pictures[0].url%>
              <% end %>
              <div class="card-city"> <%= f.city %></div>
            </div>
            <div>
              <div class="card-description"> <%= f.key_description %> <br> <strong><%= f.price %></strong> </div>
              <div class="card-rating">
                <% if f.average_rating != nil %>
                  <% (f.average_rating).times do %>
                    <i class="fas fa-star" style="color: #ffb400"></i>
                  <% end %>
                  <% (5 - f.average_rating).times do %>
                    <i class="far fa-star" style="color: #ffb400"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flat_owner_info.html.erb
<div class="header-flat-details" style="margin-top: 75px; width: 400px;">
  <div class="flat-owner-info" style="margin-right: 20px;">
    <% owner = User.find(@flat.user_id) %>
    <%= image_tag owner.photo.url, class: "img-circle", id: "owner" %>
      <p><%= owner.first_name.capitalize %> <%= owner.last_name.capitalize %></p>
  </div>

  <div class="flat-description">
    <h1 class="flat-title"><%= @flat.key_description %></h1>
    <p><%= @flat.city %></p>
    <p class="price"><%= @flat.price %></p>
    <p class="rating">
    <% if @flat.average_rating != nil %>
      <% (@flat.average_rating).times do %>
        <i class="fas fa-star" style="color: #ffb400"></i>
      <% end %>
      <% (5 - @flat.average_rating).times do %>
        <i class="far fa-star" style="color: #ffb400"></i>
      <% end %>
    <% end %> </p>
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :description %>
  <%= f.input :key_description %>
  <%= f.input :city %>
  <%= f.input :street %>
  <%= f.input :zipcode %>
  <%= f.input :price %>
  <%= f.input :guests %>
  <%= f.label :pictures %>
  <%= f.file_field :pictures, multiple: true %>
  <%= f.label :wifi %>
  <%= f.check_box :wifi %>
  <%= f.label :dishwasher %>
  <%= f.check_box :dishwasher %>
  <%= f.label :allows_pets %>
  <%= f.check_box :allows_pets %>
  <%= f.label :kitchen %>
  <%= f.check_box :kitchen %>
  <%= f.label :smoking %>
  <%= f.check_box :smoking %>
  <%= f.label :balcony %>
  <%= f.check_box :balcony %>
  <%= f.label :tv %>
  <%= f.check_box :tv %>
  <%= f.submit class: "btn btn-success" %> <%= link_to "Back to profile", my_profile_path, class: "btn btn-secondary" %>
<% end %>

app/views/users/my_profile.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<div class="profile-header-wrapper">
  <div class="profile-header-infos">
    <h1>Welcome home, <%= @user.first_name %></h1>
    </div>
  </div>
  <div class="container">
    <div class="tabbable-panel">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true" style="font-size: 16px;">My profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false" style="font-size: 16px;">My bookings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false" style="font-size: 16px;">My flats</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <!-- profile start -->
        <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
          <ul class="bookings">
            <li class="booking">
              <div class="booking-name">
                <%= image_tag @user.photo.url, class: "avatar-review" %>
              </div>
              <div class="booking-name">
                <h5>First name</h5>
                <div class="price"><%= @user.first_name%></div>
               </div>
              <div class="booking-name">
                <h5>Last name</h5>
                <div class="price"><%= @user.last_name%></div>
              </div>
              <div class="booking-name">
                <h5>Email</h5>
                <div class="price"><%= @user.email%></div>
               </div>
              <!-- profile ends -->
              <!-- bookings start -->
              <div class="booking-review">
                <%= link_to "Edit", edit_user_registration_path, class: "btn btn-secondary" %>
              </div>
            </li>
          </ul>
        </div>
        <!-- profile ends -->
        <!-- bookings start -->
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <ul class="bookings">
            <% if @user_bookings.exists? %>
              <% @user_bookings.each do |b| %>
                <li class="booking">
                  <div class="booking-name">
                    <%= image_tag b.flat.user.photo.url, class: "avatar-review" %>
                  </div>
                  <div class="booking-name">
                    <h5><%= @flats.find(b.flat_id).city%></h5>
                    <div class="price">
                      <%= @flats.find(b.flat_id).key_description %>
                    </div>
                  </div>
                  <div class="booking-review">
                    <%= link_to "Create review", new_booking_review_path(b.id), class: "s-button" %>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <!-- booking ends -->
        <!-- my flats start -->
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
          <ul class="bookings">
            <% @user_flats.each do |f| %>
            <li class="booking">
              <div class="booking-name">
               <h5>Sharing since</h5>
               <%= f.created_at.strftime("%Y-%m-%d") %>
             </div>
             <div class="booking-name">
              <%=f.key_description%>
            </div>
            <div class="booking-status">
              <% if f.average_rating != nil %>
              <div class="card-rating">
                <% (f.average_rating).times do %>
                <i class="fas fa-star" style="color: #ffb400"></i>
                <% end %>
                <% (5 - f.average_rating).times do %>
                <i class="far fa-star" style="color: #ffb400"></i>
                <% end %>
              </div>
            <% end %>
            </div>
            <div class="booking-review">
              <%= link_to "Edit", edit_flat_path(f.id), class: "btn btn-secondary" %>
            </div>
          </li>
          <% end %>
        </ul>
        <%= link_to "Create a flat", new_flat_path, class: "s-button" %>
      </div>
      <!-- my flats ends -->
    </div>
  </div>
</div>